		<!--MAIN HEADER-->
		<div id="main-header">
			<!--- Mobile Navigation-->
			<div>
				<span class="slide">
					<a href="#" id="open" onclick="openMenu()">
						<i  class="fas fa-bars"></i>
					</a>
				</span>
				<div id="menu" class="navMobile">
					<a href="#" id="close" onclick="closeMenu()">
						<i class="fas fa-times"></i>
					</a>
					
					<div class="mobileLinks">
						<a class href="index.html" > <i class="fas fa-home shiftLeft"></i> Home  </a>
						<a href="products.html"><i class="fas fa-shopping-cart shiftLeft "></i>Products</a>
						<a href="contact.html"><i class="far fa-address-card shiftLeft"></i>Contact Us</a>
					</div>
				</div>
			</div>

			<!--Desktop Navigation-->
			<div class="header">
				<div class="nav">
					<a href="index.html"> Home </a>|
					<a href="products.html"> Products </a>|
					<a href="contact.html">Contact Us</a>
				</div>
				

				<div align="center">
					<a href="index.html"><img class="headerLogo" src="css/images/logo.png"/></a>
					<hr>
				</div>
			</div>
		</div>